# Generated by Django 3.0.2 on 2020-03-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_auto_20200313_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='nome',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
