# Generated by Django 3.0.2 on 2020-03-16 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_auto_20200316_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jogo',
            old_name='nome',
            new_name='name',
        ),
    ]
